# Generated by Django 4.1.5 on 2023-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('video_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('published_time', models.DateTimeField()),
                ('thumbnails', models.JSONField()),
                ('urls', models.URLField()),
                ('channel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_id', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
