# Generated by Django 4.1.5 on 2023-01-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_data', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='youtubedata',
            index=models.Index(fields=['published_time'], name='pubtime_idx'),
        ),
    ]
