version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - SECRET_KEY='django-insecure-mbn=yq+ios7pngj531t(zk7-7xm3#6)sv$2!5s@3ef)59j$3j$'
        depends_on:
            - redis

    redis:
        image: "redis:alpine"
        expose:
            - 6379

    celery:
        build: .
        command: celery -A youtube_fetch worker -l INFO
        volumes:
            - .:/usr/src/app/
        environment:
            - DEBUG=1
        depends_on:
            - django
            - redis

    celery-beat:
        build: .
        command: celery -A youtube_fetch beat --loglevel=info
        volumes:
            - .:/usr/src/app/

        environment:
            - DEBUG=1
